spring.application.name=process-order-service

server.port=8083

#DB config
spring.datasource.url=
spring.datasource.username=
spring.datasource.password=

#config service
spring.config.import=optional:configserver:http://localhost:8763
spring.cloud.config.username=configUser
spring.cloud.config.password=password
spring.cloud.config.name=${spring.application.name}
spring.cloud.config.label=1.0.0

#retry-config
spring.cloud.config.fail-fast=false
spring.cloud.config.retry.max-attempts=6
spring.cloud.config.retry.max-interval=2000
spring.cloud.config.retry.initial-interval=1000

#graphql config
spring.graphql.graphiql.enabled=true
spring.graphql.graphiql.path=/graphiql
spring.graphql.path=/graphql
spring.graphql.schema.introspection.enabled=true

# logging level
logging.level.com.sovon9=DEBUG